name: Pull request workflow

on: pull_request

jobs:
  lint:
    name: Find linting problems in your JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: 14

      - name: Install node_modules
        run: yarn

      - name: Run ESLint check
        run: yarn run lint

  test:
    name: Running unit tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: 14

      - name: Install node_modules
        run: yarn

      - name: Run tests
        run: |
          yarn run build
          yarn run test
