name: Tag workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Creating a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Setup node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@starkware-industries'

      - name: Install dependencies
        run: yarn

      - name: Build project 🔧
        run: yarn run build

      - name: Publish package on NPM 📦
        run: yarn npm-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
